name: bbgbigwig
owner: iuc
categories:
- Convert Formats
description: Make a bigwig from bam, bed or gff, optionally with a chromosome length file.
long_description: Designed for assembly visualisation JBrowse2 workflows where dbkey is not ready to be assigned even with a custom genome
type: unrestricted
