categories:
- Sequence Analysis
description: JBrowse2 Genome Browser integrated as a Galaxy Tool
homepage_url: https://jbrowse.org
long_description: |
  JBrowse2 is a fast, extensible JS+HTML5 genome browser.

  This repository contains a tool that builds a JBrowse2 Genome Browser deployment from raw data files such as gff3, bed, bam,
  vcf, blastxml, and more - see https://jbrowse.org.

  It is based largely on Galaxy JBrowse1 tool code, and produces a ready-to-deploy HTML file and associated processed
  datasets, allowing visualization of the genome either from within Galaxy, or stand-alone sharing.

  The tool must be whitelisted for HTML content, and must be served from an apache or nginx server implementing range requests.

name: jbrowse2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/jbrowse2
type: unrestricted
